// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOtCIj1gQTyGuj2C2yUXgSnxqyrnVE1f0',
    appId: '1:168599969116:web:6e21f0b17a2da2fcd13599',
    messagingSenderId: '168599969116',
    projectId: 'universe-25a9c',
    authDomain: 'universe-25a9c.firebaseapp.com',
    databaseURL: 'https://universe-25a9c-default-rtdb.firebaseio.com',
    storageBucket: 'universe-25a9c.appspot.com',
    measurementId: 'G-1QRC2XMLX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaOLb5j-VmWQK6gff2B92r7onuYyjv_RA',
    appId: '1:168599969116:android:60a9908812090d6cd13599',
    messagingSenderId: '168599969116',
    projectId: 'universe-25a9c',
    databaseURL: 'https://universe-25a9c-default-rtdb.firebaseio.com',
    storageBucket: 'universe-25a9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTnzEQbIJ3EragU5LayMIEDeNKneUsS0E',
    appId: '1:168599969116:ios:e0a119b8fc372446d13599',
    messagingSenderId: '168599969116',
    projectId: 'universe-25a9c',
    databaseURL: 'https://universe-25a9c-default-rtdb.firebaseio.com',
    storageBucket: 'universe-25a9c.appspot.com',
    androidClientId: '168599969116-0ujlse7q24nqr5sim4jk3nd7k88frfhj.apps.googleusercontent.com',
    iosClientId: '168599969116-pmi5mrema278954r0g24v3n42p3bh45q.apps.googleusercontent.com',
    iosBundleId: 'com.aa.learningApp',
  );
}
